version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/docs/sphinx"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docs"
      include: "scope"
